//! Execution tests: run sqlser's SQL on a real engine and diff it against the
//! original query.
//!
//! `BROKEN.md` is explicit that the worst failures — a rotated column order, a
//! dropped filter, an inflated `LIMIT` — produce no error and survive a
//! round-trip check. The only thing that catches them is executing both
//! queries and comparing the results, so that is what these do.
//!
//! Engines are driven through their CLIs (`duckdb`, `psql`) rather than a
//! client crate, to keep the crate's dependency surface small. A test **skips**
//! when its engine is unreachable, following `dee/tests/adbc_smoke.rs`.

mod support;

use std::process::Command;

use sqlser::Unparser;
use sqlser::dialect::{DuckDBDialect, PostgreSqlDialect};
use support::{ctx, ctx_with, opt_plan};

/// The DuckDB TPC-H fixture, regenerated by
/// `duckdb tpch.duckdb -c "INSTALL tpch; LOAD tpch; CALL dbgen(sf=0.01)"`.
fn duck_db_path() -> Option<String> {
    let p = std::env::var("TPCH_DB").unwrap_or_else(|_| "tpch.duckdb".into());
    // Tests run from the crate directory; the fixture lives at the workspace root.
    [p.clone(), format!("../{p}")]
        .into_iter()
        .find(|c| std::path::Path::new(c).exists())
}

fn duck(sql: &str) -> Option<String> {
    let db = duck_db_path()?;
    // Read-only, because these tests run concurrently against one file and
    // DuckDB takes an exclusive lock otherwise.  The `u7` case needs temp
    // views, which a read-only *database* still allows.
    let out = Command::new("duckdb")
        .args(["-readonly", &db, "-csv", "-noheader", "-c", sql])
        .output()
        .ok()?;
    if !out.status.success() {
        return Some(format!("ERROR: {}", String::from_utf8_lossy(&out.stderr)));
    }
    Some(String::from_utf8_lossy(&out.stdout).to_string())
}

fn pg(sql: &str) -> Option<String> {
    let dsn = std::env::var("PG_DSN").unwrap_or_else(|_| {
        "postgresql://runner:password@0.0.0.0:5432/benchmark".into()
    });
    let schema = std::env::var("PG_SCHEMA").unwrap_or_else(|_| "tpch".into());
    let out = Command::new("psql")
        .args([&dsn, "-tAF,", "-v", "ON_ERROR_STOP=1", "-c",
               &format!("SET search_path = {schema}"), "-c", sql])
        .output()
        .ok()?;
    if !out.status.success() {
        let err = String::from_utf8_lossy(&out.stderr);
        // Server down or database missing: skip rather than fail.
        if err.contains("could not connect") || err.contains("does not exist") {
            return None;
        }
        return Some(format!("ERROR: {err}"));
    }
    Some(String::from_utf8_lossy(&out.stdout).to_string())
}

/// Sort the rows so comparison does not depend on an unordered query's
/// arbitrary row order — but keep each row's columns in place, since column
/// order is one of the things under test.
fn normalize(s: &str) -> Vec<String> {
    let mut rows: Vec<String> = s
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty())
        .collect();
    rows.sort();
    rows
}

macro_rules! engine_or_skip {
    ($run:expr, $sql:expr, $name:literal) => {
        match $run($sql) {
            Some(v) => v,
            None => {
                eprintln!("skipping: {} is not reachable", $name);
                return;
            }
        }
    };
}

/// Every case: run the original SQL, run sqlser's SQL, demand identical rows.
async fn assert_same_on_duckdb(sql: &str) {
    let ctx = ctx().await;
    let plan = opt_plan(&ctx, sql).await;
    let ours = Unparser::new(&DuckDBDialect::new())
        .plan_to_sql(&plan)
        .expect("lowering must succeed");

    let base = engine_or_skip!(duck, sql, "duckdb");
    let got = engine_or_skip!(duck, &ours, "duckdb");
    assert!(!got.starts_with("ERROR"), "generated SQL failed:\n{ours}\n{got}");
    assert_eq!(
        normalize(&got),
        normalize(&base),
        "result differs from the original query.\noriginal: {sql}\nsqlser:   {ours}"
    );
}

async fn assert_same_on_postgres(sql: &str) {
    let ctx = ctx().await;
    let plan = opt_plan(&ctx, sql).await;
    let ours = Unparser::new(&PostgreSqlDialect::new())
        .plan_to_sql(&plan)
        .expect("lowering must succeed");

    let base = engine_or_skip!(pg, sql, "postgres");
    let got = engine_or_skip!(pg, &ours, "postgres");
    assert!(!got.starts_with("ERROR"), "generated SQL failed:\n{ours}\n{got}");
    assert_eq!(
        normalize(&got),
        normalize(&base),
        "result differs from the original query.\noriginal: {sql}\nsqlser:   {ours}"
    );
}

// -- the four silent failures -----------------------------------------------

/// U3: `['c_name', ..., 'sum(l_quantity)']` came back with the aggregate
/// rotated to the front. Same rows, wrong columns, no error.
const Q18: &str = "SELECT c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice, \
                   sum(l_quantity) FROM customer, orders, lineitem \
                   WHERE o_orderkey IN (SELECT l_orderkey FROM lineitem \
                                        GROUP BY l_orderkey HAVING sum(l_quantity) > 300) \
                     AND c_custkey = o_custkey AND o_orderkey = l_orderkey \
                   GROUP BY c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice";

/// U4: returned 15 rows where 10 were asked for.
const LIMIT_OFFSET: &str =
    "SELECT c_custkey FROM customer ORDER BY c_custkey LIMIT 10 OFFSET 5";

/// U5: TPC-H Q22's shape. Returned 25 rows against a baseline of 3.
const ANTI_JOIN_FILTER: &str =
    "SELECT cc, count(*) FROM ( \
       SELECT substring(c_phone FROM 1 FOR 2) AS cc, c_acctbal FROM customer \
       WHERE substring(c_phone FROM 1 FOR 2) IN ('13','31','23') \
         AND NOT EXISTS (SELECT 1 FROM orders WHERE o_custkey = c_custkey) \
     ) t GROUP BY cc";

/// U6: nine columns instead of five, with `n_*` duplicated.
const CROSS_JOIN: &str = "SELECT * FROM nation n, (SELECT count(*) AS c FROM customer) x";

#[tokio::test]
async fn u3_aggregate_column_order_duckdb() {
    assert_same_on_duckdb(Q18).await;
}

#[tokio::test]
async fn u4_limit_offset_row_count_duckdb() {
    assert_same_on_duckdb(LIMIT_OFFSET).await;
}

#[tokio::test]
async fn u5_anti_join_filter_duckdb() {
    assert_same_on_duckdb(ANTI_JOIN_FILTER).await;
}

#[tokio::test]
async fn u6_cross_join_arity_duckdb() {
    assert_same_on_duckdb(CROSS_JOIN).await;
}

#[tokio::test]
async fn u3_aggregate_column_order_postgres() {
    assert_same_on_postgres(Q18).await;
}

#[tokio::test]
async fn u4_limit_offset_row_count_postgres() {
    assert_same_on_postgres(LIMIT_OFFSET).await;
}

#[tokio::test]
async fn u5_anti_join_filter_postgres() {
    assert_same_on_postgres(ANTI_JOIN_FILTER).await;
}

// -- the shapes that used to be hard errors ---------------------------------

#[tokio::test]
async fn u1_sort_on_an_unselected_column_duckdb() {
    assert_same_on_duckdb(
        "SELECT c_custkey FROM customer ORDER BY c_acctbal * 2 DESC, c_custkey LIMIT 5",
    )
    .await;
}

#[tokio::test]
async fn u2_count_over_a_narrowed_subquery_duckdb() {
    assert_same_on_duckdb(
        "SELECT count(*) FROM (SELECT c_custkey FROM customer WHERE c_acctbal > 100) x",
    )
    .await;
}

#[tokio::test]
async fn u7_view_inlining_duckdb() {
    // The OMP shape. Views are registered on both sides so the baseline and
    // the generated SQL see the same relations.
    let views = [
        ("stg_cust", "SELECT c_custkey, c_name, c_nationkey, c_acctbal, c_mktsegment FROM customer WHERE c_acctbal > -999"),
        ("stg_ord", "SELECT o_orderkey, o_custkey, o_totalprice, o_orderdate, o_orderstatus FROM orders WHERE o_orderstatus <> 'X'"),
    ];
    let sql = "SELECT s.c_nationkey, count(*) AS n, sum(o.o_totalprice) AS t \
               FROM stg_cust s JOIN stg_ord o ON s.c_custkey = o.o_custkey \
               WHERE s.c_mktsegment = 'BUILDING' GROUP BY s.c_nationkey";

    let ctx = ctx_with(false, &views).await;
    let plan = opt_plan(&ctx, sql).await;
    let ours = Unparser::new(&DuckDBDialect::new())
        .plan_to_sql(&plan)
        .expect("lowering must succeed");

    let setup: String = views
        .iter()
        .map(|(n, s)| format!("CREATE OR REPLACE TEMP VIEW {n} AS {s}; "))
        .collect();
    let base = engine_or_skip!(duck, &format!("{setup}{sql}"), "duckdb");
    let got = engine_or_skip!(duck, &format!("{setup}{ours}"), "duckdb");
    assert!(!got.starts_with("ERROR"), "generated SQL failed:\n{ours}\n{got}");
    assert_eq!(normalize(&got), normalize(&base), "sqlser: {ours}");
}

#[tokio::test]
async fn u8_filtering_on_a_window_column_duckdb() {
    assert_same_on_duckdb(
        "SELECT * FROM (SELECT o_orderkey, \
           row_number() OVER (PARTITION BY o_custkey ORDER BY o_orderkey) AS rn \
         FROM orders) t WHERE rn = 1",
    )
    .await;
}

#[tokio::test]
async fn u10_trim_duckdb() {
    assert_same_on_duckdb("SELECT trim(c_name) AS t FROM customer LIMIT 20").await;
}

#[tokio::test]
async fn u12_values_duckdb() {
    assert_same_on_duckdb("SELECT * FROM (VALUES (1,'a'),(2,'b')) AS t(x,y)").await;
}

#[tokio::test]
async fn u13_recursive_cte_duckdb() {
    assert_same_on_duckdb(
        "WITH RECURSIVE t(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM t WHERE n < 5) \
         SELECT sum(n) FROM t",
    )
    .await;
}

// -- a broad sweep, so this is not just the named bugs ----------------------

#[tokio::test]
async fn a_spread_of_shapes_on_duckdb() {
    for sql in [
        "SELECT c_nationkey, c_mktsegment, sum(c_acctbal) FROM customer GROUP BY c_nationkey, c_mktsegment",
        "SELECT DISTINCT c_nationkey, c_mktsegment FROM customer",
        "SELECT c_nationkey, count(*) AS n FROM customer GROUP BY c_nationkey HAVING count(*) > 50",
        "SELECT c.c_custkey, o.o_orderkey FROM customer c LEFT JOIN orders o ON c.c_custkey = o.o_custkey",
        "SELECT c_nationkey FROM customer UNION SELECT s_nationkey FROM supplier",
        "SELECT count(*) FROM orders WHERE o_custkey NOT IN (SELECT c_custkey FROM customer WHERE c_nationkey = 1)",
        "SELECT c_custkey, (SELECT count(*) FROM orders o WHERE o.o_custkey = c.c_custkey) AS n FROM customer c",
        "SELECT c_nationkey, c_mktsegment, count(*) FROM customer GROUP BY ROLLUP(c_nationkey, c_mktsegment)",
        "SELECT o_custkey, sum(o_totalprice) AS t, rank() OVER (ORDER BY sum(o_totalprice) DESC) AS r FROM orders GROUP BY o_custkey",
    ] {
        assert_same_on_duckdb(sql).await;
    }
}

#[tokio::test]
async fn a_spread_of_shapes_on_postgres() {
    for sql in [
        "SELECT c_nationkey, c_mktsegment, sum(c_acctbal) FROM customer GROUP BY c_nationkey, c_mktsegment",
        "SELECT DISTINCT c_nationkey, c_mktsegment FROM customer",
        "SELECT c_nationkey, count(*) AS n FROM customer GROUP BY c_nationkey HAVING count(*) > 50",
        "SELECT c_nationkey FROM customer UNION SELECT s_nationkey FROM supplier",
        "SELECT count(*) FROM orders WHERE o_custkey NOT IN (SELECT c_custkey FROM customer WHERE c_nationkey = 1)",
        "SELECT c_nationkey, c_mktsegment, count(*) FROM customer GROUP BY ROLLUP(c_nationkey, c_mktsegment)",
    ] {
        assert_same_on_postgres(sql).await;
    }
}
